language: node_js
node_js:
  - '8.9.4'
env:
  - NODE_ENV=test
before_script:
  - npm install
script:
  - npm test-coverage
  - npm run coveralls
  # - ./node_modules/jshint/bin/jshint lib/*.js
  # - ./node_modules/jshint/bin/jshint test/*.js
after_failure:
  - ls -1 log
  - cat log/*
